import { Project, LiveJob, Enquiry, WorkshopSettings } from '@/types';

export const initialSettings: WorkshopSettings = {
  workshopName: "Lathe Pattarai",
  tagline: "Precision Lathe Turning & Job Work Workshop • Erode",
  phone: "+91 6369431485",
  whatsapp: "+91 6369431485",
  email: "chandruselvam1012@gmail.com",
  address: "Perundurai Road, Erode Industrial Area, Erode, Tamil Nadu 638011",
  workingHours: "Mon - Sat: 8:30 AM - 7:30 PM",
  activeBays: 14,
  totalBays: 16,
  isoCertified: true,
  standardTolerance: "±0.005mm",
};

export const mockProjects: Project[] = [
  {
    id: "proj-1",
    slug: "textile-machinery-brass-threaded-bushing",
    title: "Precision Brass Threaded Bushing for Textile Looms",
    category: "Precision Turning",
    material: "High-Grade Brass (CW614N / C36000)",
    tolerance: "±0.005mm",
    quantity: "500 Units",
    completionDate: "2025-02-15",
    clientIndustry: "Textile Machinery (Erode & Tiruppur)",
    image: "/images/brass-components.png",
    description: "High-precision brass turned components with internal threading, micro-grooved oil retention, and tight concentricity for high-speed spinning and weaving machinery.",
    specs: [
      { label: "Outer Diameter", value: "42.00mm ± 0.005" },
      { label: "Internal Thread", value: "M28 x 1.5 Fine Pitch" },
      { label: "Surface Finish", value: "Ra 0.4 µm Ground" },
      { label: "Concentricity", value: "0.003mm Runout" },
    ],
    challenge: "Maintaining strict concentricity across thin-walled brass sleeves without chatter marks during high-speed turning.",
    solution: "Custom multi-point collet holding fixture with dedicated coolant blast ensuring zero heat deformation.",
    featured: true,
  },
  {
    id: "proj-2",
    slug: "agricultural-submersible-pump-motor-shaft",
    title: "Agricultural Submersible Pump & Motor Drive Shaft",
    category: "Heavy Duty Turning",
    material: "SS316L / EN8 Steel",
    tolerance: "±0.008mm",
    quantity: "120 Units",
    completionDate: "2025-01-28",
    clientIndustry: "Pump & Motor Manufacturing",
    image: "/images/lathe-chuck.png",
    description: "Precision turned stepped drive shaft designed for agricultural borewell submersible pumps. Features ground bearing journals, precision keyway slots, and dynamic balance.",
    specs: [
      { label: "Total Length", value: "650mm" },
      { label: "Max Diameter", value: "75.00mm" },
      { label: "Shaft Runout", value: "< 0.005mm" },
      { label: "Keyway Tolerance", value: "H7 Precision Fit" },
    ],
    challenge: "Eliminating deflection along the 650mm shaft length during heavy turning on tough stainless steel stock.",
    solution: "Used hydraulic steady rest support and dynamic carbide insert geometries optimized for vibration dampening.",
    featured: true,
  },
  {
    id: "proj-3",
    slug: "electric-motor-aluminum-end-flange",
    title: "Precision Aluminum Motor End-Shield & Flange",
    category: "Lathe Turning",
    material: "AL 6061-T6 Aluminum",
    tolerance: "±0.005mm",
    quantity: "250 Units",
    completionDate: "2025-02-02",
    clientIndustry: "Electric Motors & Industrial Drives",
    image: "/images/hero-macro-cnc.png",
    description: "Precision lathe turned motor flange and bearing housing crafted from solid billet aluminum with tight register diameters and counterbores.",
    specs: [
      { label: "Register OD", value: "145.00mm ± 0.008" },
      { label: "Bearing Bore", value: "+0.005 / -0.000mm" },
      { label: "Perpendicularity", value: "0.005mm" },
      { label: "Surface Finish", value: "Fine Turned Ra 0.8 µm" },
    ],
    challenge: "Maintaining roundness and dimensional stability across large diameter aluminum rings.",
    solution: "Two-stage roughing and stress relief followed by light spring finishing passes on custom pie jaws.",
    featured: true,
  },
  {
    id: "proj-4",
    slug: "custom-hardened-steel-tooling-die",
    title: "Hardened Tool Steel Punch Dies & Form Tooling",
    category: "Tooling & Re-tooling",
    material: "D2 Tool Steel (1.2379)",
    tolerance: "±0.005mm",
    quantity: "15 Sets",
    completionDate: "2024-12-20",
    clientIndustry: "Automotive & Sheet Metal Tooling",
    image: "/images/precision-craft.png",
    description: "Custom tooling punch die crafted from hardened D2 tool steel, vacuum heat-treated and hard-turned for sheet metal pressing lines.",
    specs: [
      { label: "Hardness", value: "HRC 60-62" },
      { label: "Profile Error", value: "< 0.005mm" },
      { label: "Surface Finish", value: "Mirror Polish Ra 0.2 µm" },
    ],
    challenge: "Hard turning material above 60 HRC without micro-chipping cutting inserts.",
    solution: "Sub-micron CBN (Cubic Boron Nitride) tool inserts with rigid lathe setup and continuous flood cooling.",
    featured: false,
  },
  {
    id: "proj-5",
    slug: "phosphor-bronze-split-bushings",
    title: "Phosphor Bronze Wear Bushings for Textile Looms",
    category: "Precision Turning",
    material: "Phosphor Bronze (PB2 / C90700)",
    tolerance: "±0.005mm",
    quantity: "800 Units",
    completionDate: "2025-01-10",
    clientIndustry: "Textile Machinery Maintenance",
    image: "/images/workshop-floor.png",
    description: "Self-lubricating phosphor bronze wear bushings with helical internal oil grooves, built for heavy load weaving looms across Erode and Tiruppur mills.",
    specs: [
      { label: "Bore Size", value: "35.00mm H7" },
      { label: "Outside Dia", value: "48.00mm r6" },
      { label: "Internal Groove", value: "Figure-8 Oil Channel" },
    ],
    challenge: "Machining continuous internal helical figure-8 oil distribution channels cleanly.",
    solution: "Specialized single-point internal threading tool setup with geared lathe screw synchronization.",
    featured: false,
  },
  {
    id: "proj-6",
    slug: "heavy-industrial-flanged-coupling-shaft",
    title: "Heavy Lathe Flanged Coupling & Stepped Shaft",
    category: "Heavy Duty Turning",
    material: "Mild Steel IS2062 / EN19",
    tolerance: "±0.010mm",
    quantity: "60 Sets",
    completionDate: "2025-02-10",
    clientIndustry: "Power Transmission & Machinery",
    image: "/images/master-machinist.png",
    description: "Heavy-duty flanged coupling turned and bored on 4-jaw chuck heavy lathe with drilled PCD bolt patterns and broached keyways.",
    specs: [
      { label: "Flange Diameter", value: "220mm" },
      { label: "Internal Bore", value: "65.00mm H7" },
      { label: "Bolt Circle PCD", value: "180mm (6 Holes)" },
    ],
    challenge: "Achieving true squareness between the internal bored diameter and large outer flange face.",
    solution: "Single-setup chucking boring and facing on heavy duty 12-foot lathe.",
    featured: false,
  },
];

export const mockLiveJobs: LiveJob[] = [
  {
    id: "job-101",
    bayNumber: "BAY 01",
    jobTitle: "Textile Loom Roller Shaft Turning",
    material: "SS 304",
    tolerance: "±0.005mm",
    progress: 78,
    status: "In Progress",
    startedTime: "08:30 AM",
    estimatedCompletion: "04:30 PM Today",
    technician: "M. Kumar",
    partReference: "LPS-TEX-304-092",
  },
  {
    id: "job-102",
    bayNumber: "BAY 03",
    jobTitle: "Brass Threaded Bushing Batch Run",
    material: "Brass CW614N",
    tolerance: "±0.008mm",
    progress: 45,
    status: "In Progress",
    startedTime: "10:15 AM",
    estimatedCompletion: "06:00 PM Today",
    technician: "R. Selvam",
    partReference: "LPS-BRS-THD-441",
  },
  {
    id: "job-103",
    bayNumber: "BAY 05",
    jobTitle: "Submersible Pump Shaft Turning - 75mm",
    material: "EN8 Carbon Steel",
    tolerance: "±0.010mm",
    progress: 92,
    status: "Quality Check",
    startedTime: "07:00 AM",
    estimatedCompletion: "02:15 PM Today",
    technician: "S. Venkatesh",
    partReference: "LPS-PMP-EN8-118",
  },
  {
    id: "job-104",
    bayNumber: "BAY 08",
    jobTitle: "Automotive Bearing Bush Retooling",
    material: "Phosphor Bronze",
    tolerance: "±0.005mm",
    progress: 15,
    status: "Setup Phase",
    startedTime: "01:00 PM",
    estimatedCompletion: "Tomorrow 11:00 AM",
    technician: "K. Anand",
    partReference: "LPS-BRG-PBZ-003",
  },
  {
    id: "job-105",
    bayNumber: "BAY 12",
    jobTitle: "Flanged Motor Coupling Batch",
    material: "Mild Steel IS2062",
    tolerance: "±0.012mm",
    progress: 100,
    status: "Completed",
    startedTime: "Yesterday",
    estimatedCompletion: "Completed",
    technician: "M. Kumar",
    partReference: "LPS-CPL-MS-029",
  },
];

export const mockEnquiries: Enquiry[] = [
  {
    id: "enq-1",
    name: "Ramesh Sundaram",
    email: "ramesh@erodepumps.com",
    phone: "+91 98765 43210",
    company: "Erode Pump Dynamics Pvt Ltd",
    serviceType: "Heavy Lathe Turning",
    message: "Requirement for turning 250 numbers of SS316 submersible pump shafts as per attached CAD drawing. Tolerance ±0.01mm.",
    status: "New",
    createdAt: "2025-02-18 10:30 AM",
  },
  {
    id: "enq-2",
    name: "Vidyut Nathan",
    email: "vnathan@tiruppurtextiles.co.in",
    phone: "+91 94440 98765",
    company: "Tiruppur Weaving Mills",
    serviceType: "Precision Brass Turning",
    message: "Looking for batch production of 1,000 brass loom bushings with M20 threading. Need lead time estimation.",
    status: "Quoted",
    createdAt: "2025-02-16 03:45 PM",
  },
];

export const mockFaqs = [
  {
    question: "Where is your lathe workshop located?",
    answer: "Our workshop is conveniently located in Erode district, Tamil Nadu (Perundurai Road Industrial Corridor), with direct highway and transport access across western Tamil Nadu's industrial hub.",
  },
  {
    question: "Which areas and districts do you serve for lathe job work?",
    answer: "We regularly cater to textile mills, pump manufacturers, agriculture equipment units, and machine builders across Erode, Tiruppur, Coimbatore, Salem, Namakkal, and Karur.",
  },
  {
    question: "Do you take jobs and batch orders from Tiruppur and Coimbatore?",
    answer: "Yes! We handle regular contract machining and repeat component batches for engineering and textile clients in Tiruppur, Coimbatore, and Salem with reliable transport dispatch.",
  },
  {
    question: "What industries do you manufacture parts for?",
    answer: "We primarily machine parts for textile & spinning machinery (rollers, spindles, gears), agricultural pumps & submersible motors (stepped shafts, sleeves), automotive components, valves, and custom machine tool repairs.",
  },
  {
    question: "What dimensional tolerances can Lathe Pattarai achieve?",
    answer: "Our calibrated precision turning bays consistently achieve dimensional accuracy down to ±0.005mm (5 microns). Every batch undergoes precision micrometer and bore gauge inspection before dispatch.",
  },
  {
    question: "What are your workshop working hours and can I get an instant quote?",
    answer: "We operate Monday through Saturday from 8:30 AM to 7:30 PM. For instant quotes, you can call us or WhatsApp your component photo/drawing to +91 63694 31485.",
  },
];

export const mockStats = [
  { label: "Active Turning Bays", value: "14 / 16" },
  { label: "Precision Tolerance", value: "±0.005mm" },
  { label: "Turnaround Lead", value: "24-48 Hours" },
  { label: "Industrial Belt", value: "Erode - Tiruppur - CBE" },
];
