import { Project, LiveJob, Enquiry, WorkshopSettings } from '@/types';

export const initialSettings: WorkshopSettings = {
  workshopName: "Lathe Pattarai",
  tagline: "Precision Machining & Subtractive Tooling Workshop",
  phone: "+91 98400 12345",
  whatsapp: "+91 98400 12345",
  email: "quotations@lathepattarai.com",
  address: "Plot 14-B, SIDCO Industrial Estate, Guindy, Chennai, Tamil Nadu 600032",
  workingHours: "Mon - Sat: 8:30 AM - 7:30 PM",
  activeBays: 14,
  totalBays: 16,
  isoCertified: true,
  standardTolerance: "±0.005mm",
};

export const mockProjects: Project[] = [
  {
    id: "proj-1",
    slug: "precision-brass-threaded-bushing",
    title: "Precision Brass Threaded Bushings & Flanged Shafts",
    category: "Precision Turning",
    material: "High-Grade Brass (CW614N / C36000)",
    tolerance: "±0.005mm",
    quantity: "500 Units",
    completionDate: "2025-02-15",
    clientIndustry: "Hydraulics & Heavy Machinery",
    image: "/images/brass-components.png",
    description: "High-precision brass turned components with intricate internal threading, micro-grooving, and strict concentricity specs for high-pressure hydraulic manifolds.",
    specs: [
      { label: "Outer Diameter", value: "42.00mm ± 0.005" },
      { label: "Internal Thread", value: "M28 x 1.5 Fine Pitch" },
      { label: "Surface Finish", value: "Ra 0.4 µm Ground" },
      { label: "Concentricity", value: "0.003mm Runout" },
    ],
    challenge: "Maintaining strict concentricity across thin-walled brass sleeves without chatter marks during high-speed diamond turning.",
    solution: "Custom multi-point collet holding fixture with high-pressure oil coolant blast, ensuring zero heat deformation.",
    featured: true,
  },
  {
    id: "proj-2",
    slug: "heavy-duty-stainless-stepped-shaft",
    title: "Heavy-Duty Stainless Steel Stepped Drive Shaft",
    category: "Heavy Duty Turning",
    material: "SS316L Stainless Steel",
    tolerance: "±0.010mm",
    quantity: "120 Units",
    completionDate: "2025-01-28",
    clientIndustry: "Marine & Pump Manufacturing",
    image: "/images/lathe-chuck.png",
    description: "Precision turned stepped drive shaft designed to withstand extreme torque in marine pump assembly. Feature fine ground bearing journals and double keyways.",
    specs: [
      { label: "Total Length", value: "650mm" },
      { label: "Max Diameter", value: "95.00mm" },
      { label: "Hardness", value: "HRC 32-35 Post Heat Treatment" },
      { label: "Keyway Tolerance", value: "H7 Fit Precision" },
    ],
    challenge: "Eliminating deflection along the 650mm shaft length during heavy roughing cuts on tough SS316L stock.",
    solution: "Used hydraulic steady rest support and dynamic carbide insert geometries optimized for chip control.",
    featured: true,
  },
  {
    id: "proj-3",
    slug: "aerospace-grade-aluminum-flange",
    title: "Aerospace Grade Aluminum Aircraft Actuator Collar",
    category: "CNC Milling & Turning",
    material: "AL 7075-T6 Aerospace Aluminum",
    tolerance: "±0.005mm",
    quantity: "250 Units",
    completionDate: "2025-02-02",
    clientIndustry: "Aerospace Components",
    image: "/images/hero-macro-cnc.png",
    description: "Ultra-lightweight precision aircraft collar machined from solid 7075-T6 aluminum billet with anodized surface protection and custom counterbores.",
    specs: [
      { label: "Weight Spec", value: "185 grams ± 1g" },
      { label: "Bore Tolerance", value: "+0.005 / -0.000mm" },
      { label: "Anodizing", value: "MIL-A-8625 Type III Hardcoat" },
      { label: "Testing", value: "100% CMM Inspected" },
    ],
    challenge: "Internal stress relief during deep metal removal causing micro warping across thin flange web.",
    solution: "Iterative roughing with thermal stabilization pauses followed by light spring finishing passes.",
    featured: true,
  },
  {
    id: "proj-4",
    slug: "custom-hardened-steel-tooling-die",
    title: "Hardened Steel Custom Form Tooling & Punch Dies",
    category: "Tooling & Re-tooling",
    material: "D2 Tool Steel (1.2379)",
    tolerance: "±0.002mm",
    quantity: "15 Sets",
    completionDate: "2024-12-20",
    clientIndustry: "Automotive Stamping",
    image: "/images/precision-craft.png",
    description: "Custom tooling punch die crafted from hardened D2 tool steel, vacuum heat-treated and hard-turned for sheet metal pressing lines.",
    specs: [
      { label: "Hardness", value: "HRC 60-62" },
      { label: "Profile Error", value: "< 0.003mm" },
      { label: "Surface Finish", value: "Mirror Polish Ra 0.1 µm" },
    ],
    challenge: "Machining complex radius profiles directly on HRC 60+ hardened tool steel.",
    solution: "Hard turning with CBN (Cubic Boron Nitride) insert tooling, eliminating secondary grinding steps.",
    featured: false,
  },
];

export const mockLiveJobs: LiveJob[] = [
  {
    id: "job-101",
    bayNumber: "BAY 01",
    jobTitle: "Hydraulics Flange Shaft Turning",
    material: "SS 316L",
    tolerance: "±0.005mm",
    progress: 78,
    status: "In Progress",
    startedTime: "08:30 AM",
    estimatedCompletion: "04:30 PM Today",
    technician: "M. Kumar",
    partReference: "LPS-FLG-316L-092",
  },
  {
    id: "job-102",
    bayNumber: "BAY 03",
    jobTitle: "Brass Threaded Sleeve Batch Run",
    material: "Brass CW614N",
    tolerance: "±0.008mm",
    progress: 45,
    status: "In Progress",
    startedTime: "10:15 AM",
    estimatedCompletion: "06:00 PM Today",
    technician: "R. Selvam",
    partReference: "LPS-BRS-THD-441",
  },
  {
    id: "job-103",
    bayNumber: "BAY 05",
    jobTitle: "Heavy Lathe Chucking - 95mm Shaft",
    material: "EN24 Hardened Steel",
    tolerance: "±0.010mm",
    progress: 92,
    status: "Quality Check",
    startedTime: "07:00 AM",
    estimatedCompletion: "02:15 PM Today",
    technician: "S. Venkatesh",
    partReference: "LPS-SHT-EN24-118",
  },
  {
    id: "job-104",
    bayNumber: "BAY 08",
    jobTitle: "Automotive Bearing Bush Retooling",
    material: "Phosphor Bronze",
    tolerance: "±0.005mm",
    progress: 15,
    status: "Setup Phase",
    startedTime: "01:00 PM",
    estimatedCompletion: "Tomorrow 11:00 AM",
    technician: "K. Anand",
    partReference: "LPS-BRG-PBZ-003",
  },
  {
    id: "job-105",
    bayNumber: "BAY 12",
    jobTitle: "Custom Flanged Coupling Batch",
    material: "Mild Steel IS2062",
    tolerance: "±0.012mm",
    progress: 100,
    status: "Completed",
    startedTime: "Yesterday",
    estimatedCompletion: "Completed",
    technician: "M. Kumar",
    partReference: "LPS-CPL-MS-502",
  },
];

export const mockEnquiries: Enquiry[] = [
  {
    id: "enq-1",
    name: "Ramesh Sundaram",
    email: "ramesh@chennaipumps.com",
    phone: "+91 98765 43210",
    company: "Chennai Pump Dynamics Pvt Ltd",
    serviceType: "Heavy Lathe Turning",
    message: "Requirement for turning 250 numbers of SS316 pump shafts as per attached CAD drawing. Tolerance ±0.01mm.",
    status: "New",
    createdAt: "2025-02-18 10:30 AM",
  },
  {
    id: "enq-2",
    name: "Vidyut Nathan",
    email: "vnathan@autoengineering.co.in",
    phone: "+91 94440 98765",
    company: "Auto Precision Engineering",
    serviceType: "Brass Component Fabrication",
    message: "Looking for batch production of 1,000 brass bushings with M20 threading. Need lead time estimation.",
    status: "Quoted",
    createdAt: "2025-02-16 03:45 PM",
  },
];

export const mockFaqs = [
  {
    question: "What dimensional tolerances can Lathe Pattarai achieve?",
    answer: "Our calibrated precision turning bays consistently achieve dimensional accuracy down to ±0.005mm (5 micrometers). Each precision job undergoes optical micrometer and CMM inspection before release.",
  },
  {
    question: "What materials do you machine in your workshop?",
    answer: "We turn and mill stainless steel (SS304, SS316L, 17-4PH), alloy steels (EN19, EN24, D2), high-grade brass (C36000), bronze alloys, aircraft aluminum (6061-T6, 7075-T6), and engineering plastics (Delrin/POM, Nylon).",
  },
  {
    question: "Do you accept single-piece custom prototyping and repair jobs?",
    answer: "Yes! We specialize in both emergency single-piece prototype retooling and high-volume component production runs.",
  },
  {
    question: "How fast can I get a quotation for technical CAD drawings?",
    answer: "Our engineering team reviews submitted CAD files/drawings within 2 to 4 business hours and sends complete itemized cost estimates along with raw material specs.",
  },
];

export const mockStats = [
  { label: "Active Turning Bays", value: "14 / 16" },
  { label: "Precision Tolerance", value: "±0.005mm" },
  { label: "Turnaround Lead", value: "48 Hours" },
  { label: "Guindy SIDCO Unit", value: "Plot 14-B" },
];
