/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#231b00",
        "secondary-fixed": "#e3e2e4",
        "surface": "#f9f9ff",
        "on-primary-fixed-variant": "#52461f",
        "on-error": "#ffffff",
        "tertiary-container": "#bbb6d9",
        "surface-container-low": "#f1f3fc",
        "primary": "#6a5d34",
        "tertiary-fixed": "#e4dfff",
        "on-secondary": "#ffffff",
        "background": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#5e5b7a",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#464749",
        "on-background": "#181c22",
        "on-surface-variant": "#4b463b",
        "surface-container": "#ebedf7",
        "secondary": "#5e5e61",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#c8c2e6",
        "outline-variant": "#cdc6b7",
        "on-tertiary-container": "#4a4764",
        "on-secondary-fixed": "#1b1c1e",
        "on-secondary-container": "#626265",
        "surface-bright": "#f9f9ff",
        "error": "#ba1a1a",
        "surface-container-highest": "#e0e2eb",
        "inverse-surface": "#2d3037",
        "on-surface": "#181c22",
        "surface-dim": "#d7dae3",
        "inverse-on-surface": "#eef0fa",
        "primary-fixed-dim": "#d7c594",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "inverse-primary": "#d7c594",
        "secondary-container": "#e0dfe2",
        "on-tertiary-fixed-variant": "#464361",
        "on-tertiary-fixed": "#1b1833",
        "on-primary-container": "#554922",
        "surface-container-high": "#e6e8f1",
        "secondary-fixed-dim": "#c7c6c9",
        "primary-container": "#cab988",
        "outline": "#7c776a",
        "surface-tint": "#6a5d34",
        "primary-fixed": "#f4e1ad",
        "surface-variant": "#e0e2eb"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "margin-mobile": "1.25rem",
        "margin": "3rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "gutter": "1.5rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "space-2xl": "4rem"
      },
      fontFamily: {
        "body-sm": ["var(--font-be-vietnam)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-space-grotesk)", "sans-serif"],
        "editorial-accent": ["var(--font-playfair)", "serif"],
        "headline-sm": ["var(--font-space-grotesk)", "sans-serif"],
        "body-lg": ["var(--font-be-vietnam)", "sans-serif"],
        "display-xl-mobile": ["var(--font-space-grotesk)", "sans-serif"],
        "display-xl": ["var(--font-space-grotesk)", "sans-serif"],
        "headline-md": ["var(--font-space-grotesk)", "sans-serif"],
        "label-technical": ["var(--font-space-grotesk)", "sans-serif"],
        "body-md": ["var(--font-be-vietnam)", "sans-serif"],
        "headline-lg": ["var(--font-space-grotesk)", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "editorial-accent": ["15px", { lineHeight: "22px", letterSpacing: "0.02em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "display-xl-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "display-xl": ["64px", { lineHeight: "72px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-technical": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" }]
      }
    }
  },
  plugins: []
};
